### PR TITLE
Remove NodeStateSnapshot

### PR DESCRIPTION
**Pull request by RNabel**
Closes https://github.com/quickwit-oss/chitchat/issues/149

### CODE REVIEW

**Comment by fulmicoton** [comment]
thank you @RNabel

**Comment by RNabel** [comment]
Fixed the format error and marked the PR as ready for review

**Comment by RNabel** [comment]
Friendly ping @fulmicoton

**Comment by fulmicoton** [comment]
sorry i had totally missed your ping!

**Review by fulmicoton — APPROVED** [review]

**Pull request merged**
